### ISSUE TITLE
Cannot install CachyOS in VMWare Workstation Pro 17

### ISSUE THREAD

**Issue by Marin-Kitagawa** [CachyOS/distribution#1]
I expected a smooth installation of CachyOS. I selected Hyprland and in the next screen I selected KDE, Sway, Wayfire and Openbox (just wanted to try them out). I tried to install it thrice. I always chose `systemd-boot` as the bootloader. I was never able to install it. The following link points to the log: [Installation Log](http://termbin.com/n678). I am really upset with this experience given that you advertise this as blazingly fast linux distro. But even the installer takes $\ge 5$ minutes to load given the below specs for the Virtual Machine (the same specs all throughout 3 tries; after deleting the previous VM completely from disk due to failure):

RAM: 11256 MB
HDD (VM is placed inside an SSD): 1033 GB
3D acceleration for Graphics enabled
USB 3.1 compatible
UEFI
And the rest of them are defaults.
Other Linux 5.x Kernel 64 -bit chosen

Also, no kernel chosen other than the default one i.e. Kernel settings left to default

Version of CachyOS: $230319$

**Comment by vnepogodin** [comment]
Hi @Marin-Kitagawa 

As mentioned above you cannot install multiple desktop environments.
> But even the installer takes $\ge 5$ minutes to load given the below specs for the Virtual Machine
The time installer takes to launch directly depends on the speed of your internet connection as it fetches every time the latest installer.

Any Wayland compositors does not work in VMs, except only Gnome works in VMs. Due to the fact that Wayland compositors need DRM device, basically they require GPU acceleration which VMs does not have (unless you by-pass your GPU to the VM)

**Comment by vnepogodin** [comment]
Well you can install, but it won't start in a VM

**Comment by Marin-Kitagawa** [comment]
I didn't choose Hyprland now. Yet, I get this [error](https://termbin.com/a8ln). I chose Sway, Wayfire, KDE, OpenBox

**Comment by vnepogodin** [comment]
You cannot select multiple multiple desktop environments as mentioned some msgs before.
":: cachyos-kde-settings and cachyos-openbox-settings are in conflict"

**Comment by Marin-Kitagawa** [comment]
> Oh why? I really like to have them both. Is it because of `x11` and `Wayland`? If so, can't it be configured to install only Plasma Wayland and Hyprland? Also, is it ok if I choose multiple WMs even if I uncheck KDE? I have faced this issue in Arcolinux as well. I was not even able to enter into Hyprland. I had KDE and a lot of WMs installed

Why though? Arcolinux allows me to install a whole lost of WMs as mentioned here. Could you make it more compatible? You mentioned "desktop environments". But except KDE all others are WMs. That's why I have mentioned the above as well.

**Comment by ptr1337** [comment]
> > Oh why? I really like to have them both. Is it because of `x11` and `Wayland`? If so, can't it be configured to install only Plasma Wayland and Hyprland? Also, is it ok if I choose multiple WMs even if I uncheck KDE? I have faced this issue in Arcolinux as well. I was not even able to enter into Hyprland. I had KDE and a lot of WMs installed
> 
> Why though? Arcolinux allows me to install a whole lost of WMs as mentioned here. Could you make it more compatible? You mentioned "desktop environments". But except KDE all others are WMs. That's why I have mentioned the above as well.

You can just untick the cachyos-*-desktop settings. Then it will work fine. But you won't get any dotfiles.
