### ISSUE TITLE
[Question] Bootstrap fresh installation with CachyOS repos?

### ISSUE THREAD

**Issue by GrabbenD** [CachyOS/distribution#10]
I'm trying to build a new rootfs directly with CachyOS binaries (to avoid first using Arch Linux repository and then overwriting it with equivalents from CachyOS).

Do you know if this approach is doable?
```console
$ export BUILDDIR=/mnt
$ pacman-key --gpgdir ${BUILDDIR}/etc/pacman.d/gnupg --init
$ pacman-key --gpgdir ${BUILDDIR}/etc/pacman.d/gnupg --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
$ pacman-key --gpgdir ${BUILDDIR}/etc/pacman.d/gnupg --lsign-key F3B607488DB35A47
$ mkdir -pv ${BUILDDIR}/var/lib/pacman
$ pacman --noconfirm -r ${BUILDDIR} -U 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-3-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-17-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v3-mirrorlist-17-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v4-mirrorlist-5-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-6.0.2-11-x86_64.pkg.tar.zst'

warning: database file for 'core' does not exist (use '-Sy' to download)
warning: database file for 'extra' does not exist (use '-Sy' to download)
loading packages...
error: '/var/cache/pacman/pkg/cachyos-keyring-3-1-any.pkg.tar.zst': invalid or corrupted package (PGP signature)
error: '/var/cache/pacman/pkg/cachyos-mirrorlist-17-1-any.pkg.tar.zst': invalid or corrupted package (PGP signature)
error: '/var/cache/pacman/pkg/cachyos-v3-mirrorlist-17-1-any.pkg.tar.zst': invalid or corrupted package (PGP signature)
error: '/var/cache/pacman/pkg/cachyos-v4-mirrorlist-5-1-any.pkg.tar.zst': invalid or corrupted package (PGP signature)
error: '/var/cache/pacman/pkg/pacman-6.0.2-11-x86_64.pkg.tar.zst': invalid or corrupted package (PGP signature)
```

**Comment by ptr1337** [comment]
Hi,

actually this wont really work, since we dont have all packages in our repository.
Mainly *-any packages currently, since they dont provide any optimization attempt.

Its a idea to get completely independent someday, but currently this is not possible :(

**Comment by GrabbenD** [comment]
@ptr1337 That's understandable!
I'm actually trying to mix CachyOS and Arch Linux repos (as outlined in https://wiki.cachyos.org/en/home/Repo) while building a fresh rootfs but Pacman complains about `invalid or corrupted package (PGP signature)`. Do you know from your experience what could be wrong?

**Comment by GrabbenD** [comment]
Thanks, it was useful @ptr1337 
The remaining problem is that Pacman still uses `/` as the root and not `/mnt` while I'm attempting to build my rootfs:
```
fakechroot fakeroot pacman \
    -r /mnt \
    --noconfirm \
    --dbpath /mnt/var/lib/pacman \
    --config /mnt/etc/pacman.conf \
    --cachedir /mnt/var/cache/pacman/pkg \
    --noscriptlet \
    --hookdir /mnt/etc/pacman.d/hooks \
    -Sy

error: config file /etc/pacman.d/cachyos-v3-mirrorlist could not be read: No such file or directory
```

Do you know if there's any way to make Pacman think `/mnt` is `/` without chroot?

**Comment by ptr1337** [comment]
You can use pacstrap for it, if im not wrong.

**Comment by GrabbenD** [comment]
Great idea @ptr1337 
I gave that a shot but it doesn't work inside a container as it tries to mount paths which aren't available. Furthermore another problem is that it uses Pacman config from the host and not the build directory 🙁
