### ISSUE TITLE
[Question] x86_64-v3 build flags for Sway?

### ISSUE THREAD

**Issue by GrabbenD** [CachyOS/distribution#13]
Hey there
Absolutely love this project and got a usage question.

I'm building my own Sway with custom patches to [prevent the cursor from breaking VRR](https://github.com/swaywm/sway/issues/7714#issuecomment-1694356639) and due to this I'm using Pacman's makepkg build flags which by default aren't the same as build flags which you're using to build Sway/Wlroots (since I added CachyOS repositories to a existing Arch Linux installation).

Where can I find which flags you've used to build Sway/Wlroots in your x86_64-v3/lto repository?

**Comment by ptr1337** [comment]
Here you can find the used makepkg.conf:
https://paste.cachyos.org/p/37c876f.log

**Comment by GrabbenD** [comment]
You're fast wow, thanks a ton!
Isn't this file anywhere in Github?
Figured it might be beneficial to provide a link which is always up to date for future reference :)

**Comment by ptr1337** [comment]
> You're fast wow, thanks a ton! Isn't this file anywhere in Github? Figured it might be beneficial to provide a link which is always up to date for future reference :)

It is currently only set locally on our server.
Basically the only changes are that we are using relative-locks at the LDFLAGS. Arch want to do this with devtools 1.10.

Also "lto" is enabled as default, but this is also in arch's devtools config, but not on their pacman makepkg.conf.

on top the -march is changed to x86-64-v3 and -mtune=haswell (skylake mtune did bring somehow issues on some packages :( )

**Comment by GrabbenD** [comment]
Thanks for the insights!

> we are using relative-locks at the LDFLAGS

Out of curiosity, what's the benefit of doing this apart from [reduced size of libraries](https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/188)?

> Also "lto" is enabled as default, but this is also in arch's devtools config

Just to clarify, I don't have to make any changes to devtools config in that case (even if I installed CachyOS repository in a existing Arch Linux setup)?

> on top the -march is changed to x86-64-v3 and -mtune=haswell

Completely forgot about the default `-march=native` in `/etc/makepkg.conf`!
In that case and apart from relative locks - I suppose I don't have to make any changes at all to get CachyOS's performance benefits while building locally?

**Comment by ptr1337** [comment]
> Thanks for the insights!
> 
> > we are using relative-locks at the LDFLAGS
> 
> Out of curiosity, what's the benefit of doing this apart from [reduced size of libraries](https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/188)?
> 
> > Also "lto" is enabled as default, but this is also in arch's devtools config
> 
> Just to clarify, I don't have to make any changes to devtools config to enable LTO (even if I installed CachyOS repositories manually in a existing Arch Linux setup)?
> 
> > on top the -march is changed to x86-64-v3 and -mtune=haswell
> 
> Completely forgot about the default `-march=native` in `/etc/makepkg.conf`! In that case and apart from relative locks - I suppose I don't have to make any changes at all to get CachyOS's performance benefits while building locally?

Hi,

Sorry for the late reply. I did over read it.

1. Relative locks does only reduce the binary size
2. If you are using devtools to build (in a chroot) you need to define a makepkg.conf or you adjust it in /usr/share/devtools/makepkg.conf (or something like that). It wont use the /etc/makepkg.conf.
3. Our pacman makepkg.conf does already enable LTO and -march=native as default. There is nothing to do, as long you build with makepkg and not inside a chroot. If chroot see above.
