### ISSUE TITLE
[Question] Clear Linux package patches?

### ISSUE THREAD

**Issue by GrabbenD** [CachyOS/distribution#14]
From my understanding CachyOS has adopted Clear Linux's kernel optimizations and similar compiler flags.

**What about regular packages in CachyOS, are they using Clear Linux's patches for PKGBUILD?**
https://github.com/clearlinux-pkgs/linux

For reference, Clear Linux in a container (without a kernel) has performance advantage due to its compiler flags and also patched packages:
https://www.phoronix.com/forums/forum/software/distributions/1303724-benchmark-benefits-of-clear-linux-containers-distrobox

**Comment by ptr1337** [comment]
> From my understanding CachyOS has adopted Clear Linux's kernel optimizations and similar compiler flags.
> 
> **What about regular packages in CachyOS, are they using Clear Linux's patches for PKGBUILD?** https://github.com/clearlinux-pkgs/linux
> 
> For reference, Clear Linux in a container (without a kernel) has performance advantage due to its compiler flags and also patched packages: https://www.phoronix.com/forums/forum/software/distributions/1303724-benchmark-benefits-of-clear-linux-containers-distrobox

Hi,

We use a selection of their patches, but many of them are adjusted to their needs. 
This patch need to be added back to our kernel:
https://github.com/clearlinux-pkgs/linux/blob/main/0121-locking-rwsem-spin-faster.patch

Another one, which would be worth is following:
https://github.com/clearlinux-pkgs/linux/blob/main/0162-extra-optmization-flags.patch

But this patch won't be compatible, when the kernel is build with llvm, sadly.

**Comment by GrabbenD** [comment]
Glad to hear you have that covered :)
