### ISSUE TITLE
Add gamescope (non -git)

### ISSUE THREAD

**Issue by John-Gee** [CachyOS/distribution#15]
Hey,

You already have the -git version, it'd be nice to add the non-git one which is hopefully more stable.
It's already part of extra.

Thanks!

**Comment by ptr1337** [comment]
> Hey,
> 
> You already have the -git version, it'd be nice to add the non-git one which is hopefully more stable. It's already part of extra.
> 
> Thanks!

Hi,

gamescope is in the default arch repository. It is currently not in "cachyos-extra-v3" since the compilation failed with the rebuild.
This should be fixed in the future with newer releases.

**Comment by John-Gee** [comment]
Oh my bad.
Where can I check the list of packages you should have to not bother you
again?
Thank you!
