### ISSUE TITLE
manpages in `cachyos-v3/binutils` are empty

### ISSUE THREAD

**Issue by MithicSpirit** [CachyOS/distribution#18]
The manpages in the `cachyos-v3/binutils` package are empty on my machine. This means that running something like `man as` causes it to open a blank file in my manpager and then print out the following error when I exit.
```
man: command exited with status 1: (cd /usr/share/man && /usr/lib/man-db/zsoelim) | (cd /usr/share/man && /usr/lib/man-db/manconv -f UTF-8:ISO-8859-1 -t UTF-8//IGNORE) | (cd /usr/share/man && preconv -e UTF-8) | (cd /usr/share/man && tbl) | (cd /usr/share/man && nroff -mandoc -rLL=78n -rLT=78n -P -c -Tutf8)
```
This issue does not occur in `cachyos-core-v3/binutils` nor in Arch's `core/binutils`.

**Comment by ptr1337** [comment]
Fixed is pushed, please update binutils and check.

Thanks for the report

**Comment by MithicSpirit** [comment]
Working for me. Thanks!
