### ISSUE TITLE
Confirmation mails broken

### ISSUE THREAD

**Issue by svenha** [CachyOS/distribution#2]
For new forum users, the button "resend confirmation mail" leads to an error.

**Comment by ptr1337** [comment]
> For new forum users, the button "resend confirmation mail" leads to an error.

HI.
That is a known issue. We planned to migrate to another mailserver and also to a different forum software soon.

**Comment by svenha** [comment]
Thanks for the answer. Please let us know when the migration is done - for all the new users waiting to participate in the forum :-)

**Comment by ptr1337** [comment]
> Thanks for the answer. Please let us know when the migration is done - for all the new users waiting to participate in the forum :-)

Hi

I keep them activating manually. So you should be just able to login.

**Comment by ptr1337** [comment]
Hi,

Issues is resolved. It does not require a activiation mail anymore for now.
