### ISSUE TITLE
star citizen : gnome + wayland

### ISSUE THREAD

**Issue by Frmahe** [CachyOS/distribution#22]
Hello 

When I launch the game in Lutris "Star Citizen" with a Gnome + Wayland section, an area of the game is not clickable everything works fine on KDE and on Gnome X11 

(AMD video card)
![starcitizen](https://github.com/CachyOS/distribution/assets/170797171/90248a7a-80bf-484e-9494-fd4397d94a8a)

**Comment by ptr1337** [comment]
I think you should report this to the gnome developers, specially if it works with KDE and Gnome X11.

**Comment by Frmahe** [comment]
I'm having the problem on Cachyos. I tried on ubuntu and fedora and everything works

**Comment by ptr1337** [comment]
We are not modifying GNOME in any way. Its complete stock and now additional patches applied.
Also, without proper logs or equal its hard to help here.

**Comment by Frmahe** [comment]
Ok thank you

**Comment by Username404-59** [comment]
> When I launch the game in Lutris "Star Citizen" with a Gnome + Wayland section, an area of the game is not clickable everything works fine on KDE and on Gnome X11

Are you running it with wayland or xwayland?
I have this issue with winewayland.drv too on gentoo so I believe this isn't specific to cachyos

**Comment by 404Fox** [comment]
Have you visited the SC Linux users group? They have a wiki for known issues and troubleshooting SC on linux, and you might find someone who had the same issue in their discord/matrix.
https://github.com/starcitizen-lug/knowledge-base/wiki
