### ISSUE TITLE
Brave Browser be compiled with v3 flag.

### ISSUE THREAD

**Issue by iHarryPotter178** [CachyOS/distribution#23]
i'm a noob in linux, especially arch, I just switched to Cachy today, but noticed that Brave Browser, which I use extensively, isn't in the v3 optimized repo.
Can this be compiled for future buids.

**Comment by vnepogodin** [comment]
Hi @iHarryPotter178 

there are no proper PKGBUILD available for brave for us to compile, and it takes quite much time to build it.
so we just repackage brave binaries built by Brave
