### ISSUE TITLE
btrfs assistant don't work at boot time

### ISSUE THREAD

**Issue by heheda123123** [CachyOS/distribution#26]
1 create an config below
![image](https://github.com/user-attachments/assets/939dd8fb-b4be-48d1-8b9d-2122e315ae73)
2 after reboot ,wait 10 minutes, still not have new snapshot
3 use systemctl check service/timer status
![image](https://github.com/user-attachments/assets/df5caff4-f0b5-44c5-b7d8-dd495b01f337)
the output shows that, only /etc/snapper/configs/root exist can trigger boot snapshot. 
only  /etc/snapper/configs/(config name) in that directory.

Is this a bug?

**Comment by Pogogo007** [comment]
Name your config root. This is what snapper expects.
