### ISSUE TITLE
python-pillow 9.5.0 : PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by sanitizer84** [CachyOS/distribution#3]
I got this error: PIL.UnidentifiedImageError: cannot identify image file while reading pics from a directory using "from PIL import Image;
im = Image.open('some file name') ". cachyos-v3/pillow 9.5.0 was installed. After downgraded to community/pillow 9.4.0, the error did not appear.

**Comment by ptr1337** [comment]
> I got this error: PIL.UnidentifiedImageError: cannot identify image file while reading pics from a directory using "from PIL import Image; im = Image.open('some file name') ". cachyos-v3/pillow 9.5.0 was installed. After downgraded to community/pillow 9.4.0, the error did not appear.

Hi, thanks for reporting this issue.

Somehow it seems like that arch did updated (https://github.com/archlinux/svntogit-community/commit/417c086ea9690c681ac3f1992a9fbd6af3daf929) but not pushed it into their database ?!

Anyways - We will block and remove the package for now, till arch does proper update their db :)
