### ISSUE TITLE
OBS NVIDIA Encoders missing (I reported to OBS on github as well, they directed me here)

### ISSUE THREAD

**Issue by Gamma195** [CachyOS/distribution#43]
Hello!

This is my first time reporting something, so if I don't provide everything I apologize. I reported this to OBS - and they told me to come to the Distro distributor.

I recently updated my system (I'm fairly new to Linux. Only been on it for a few weeks daily driving it), and everything was working as it should but after the update last night for OBS, it appears that my encoders went missing. I previously had NVENC and NVENC HVEC, along with several others - and they are now missing. There was also a change to the preset - which I am confused on the naming change.

My system specs:
OS: CachyOS
KERNEL: 6.10.1-2-cachyos
CPU: AMD Ryzen 9 7900X 12-Core
GPU: NVIDIA GeForce RTX 4080
GPU DRIVER: NVIDIA 560.31.02
RAM: 32 GB

CachyOS Bug report:
https://paste.cachyos.org/p/32a5e6f

OBS Log:
[2024-08-11 05-08-40.txt](https://github.com/user-attachments/files/16573233/2024-08-11.05-08-40.txt)
[2024-08-11 05-06-14.txt](https://github.com/user-attachments/files/16573234/2024-08-11.05-06-14.txt)
[2024-08-06 10-31-37.txt](https://github.com/user-attachments/files/16573235/2024-08-06.10-31-37.txt)

**Comment by ptr1337** [comment]
Hi,

The NVIDIA driver got yesterday updated to 560. I just made a quick look into my system, with a 4070S and following encoder are present.
![image](https://github.com/user-attachments/assets/358375a5-97f6-4c4e-9138-0ea4b4613aa0)


I will look later a bit deeper nito it. Just as sanity check - did you reboot your system after updating?

**Comment by ventureoo** [comment]
Can you try run `sudo nvidia-modprobe -c0 -u` before running OBS?

**Comment by Gamma195** [comment]
Yep I rebooted and everything. One of my buddies had me throw this in the terminal, and it got all my encoders back :D

sudo pacman -S lib32-obs-vkcapture-git obs-gstreamer obs-plugin-looking-glass-git obs-rtspserver obs-streamfx-unstable obs-studio-stable obs-vaapi
