### ISSUE TITLE
Pamac-GUI not starting

### ISSUE THREAD

**Issue by Taddaeus** [CachyOS/distribution#53]
Some weeks ago the pamac-GUI "Software hinzufügen/entfernen" refuses to start on two different installations of CachyOS simultaneously. Also with VPN and firewall deactivated.

https://paste.cachyos.org/p/2b2327c.log

![Screenshot_20241112_111234](https://github.com/user-attachments/assets/801b44da-3d69-4552-af6f-ce494a060b3f)

**Comment by ptr1337** [comment]
Please update and recheck
