### ISSUE TITLE
Can't install from Ventoy

### ISSUE THREAD

**Issue by Mooling0602** [CachyOS/distribution#56]
![IMG_20241125_124321.jpg](https://github.com/user-attachments/assets/19be3537-4585-427d-b6e6-430969c112e7)

**Comment by dougg0k** [comment]
Here, I installed from it, works fine. Make sure it's the latest version. They have a tool to update.

**Comment by Mooling0602** [comment]
> Here, I installed from it, works fine. Make sure it's the latest version. They have a tool to update.

Okay I'll try.
