### ISSUE TITLE
[Proporsal] removal of fastfetch from being printed with every new terminal session

### ISSUE THREAD

**Issue by lunelovehearn** [CachyOS/distribution#61]
greetings. after running my test of cachy, I found this very annoying. I know it's useful for other users, but some others like me, may just want to get things done. 
now to clarify: users may want to keep fish and the configuration, but just not want to have fastfetch to show with every new session. 
I'm aware that users can modify their config files, but consider that not every user knows how to, and in the long run, it may annoy more users who only want things done.

I'm also aware that you can unselect the ricing from calamares, but a regular new users won't read and speedrun the installation, then complain about this. this is something to consider, as there's a wide range of users with different tech knowledge levels, from zero to seasoned users.

wishing the best,
best regards.

**Comment by 1Naim** [comment]
I think you haven't tested it enough, as it is very explicitly shown in the config to disable it https://github.com/CachyOS/cachyos-fish-config/blob/main/config.fish#L5-L7, `~/.config/fish/config.fish`
