### ISSUE TITLE
[ISO Improvement] Add a calamares shortcut to the desktop and kickoff on plasma

### ISSUE THREAD

**Issue by lunelovehearn** [CachyOS/distribution#62]
when testing the ISO, I noticed that there's no entry for calamares on kickoff menu when searching for it, nor on desktop. 
my reasoning for it being added is that the welcome app tends to crash time to time, and even refuses to launch, leaving the user with no option to install the system.

another reason, is calamares crashing randomly when using it on the select keyboard layout, killing alacritty and the welcome app with it.

this happened on real hardware and on a VM. 

a reboot may fix this, but it may happen again.

**Comment by vnepogodin** [comment]
the only correct way to launch installer is via Hello app. the crashing was fixed in Hello but for that to be fixed on the ISO - new ISO release is required

it is happening due to your network issues, we cannot help with that

**Comment by lunelovehearn** [comment]
> the only correct way to launch installer is via Hello app. the crashing was fixed in Hello but for that to be fixed on the ISO - new ISO release is required
> 
> it is happening due to your network issues, we cannot help with that

it doesn't happen due to network, as the network works fine. 
I still think that giving another way to launch calamares is good, and relying on another app that could crash any time is not a good way to install a system.

**Comment by vnepogodin** [comment]
> > the only correct way to launch installer is via Hello app. the crashing was fixed in Hello but for that to be fixed on the ISO - new ISO release is required
> > it is happening due to your network issues, we cannot help with that
> 
> it doesn't happen due to network, as the network works fine. I still think that giving another way to launch calamares is good, and relying on another app that could crash any time is not a good way to install a system.

Apparently if it crashed on you, its your network issues because it fails to get ISO version from the endpoint. If we make script to launch installer, then curl will error out and nothing will happen. Its not a solution, it changes nothing
