### ISSUE TITLE
Legion Go : no bluetooth

### ISSUE THREAD

**Issue by SeeDborg** [CachyOS/distribution#67]
Hi,
Bluetooth does not seem to work on Lenovo Legion Go.

No peripheral is detected.
I can turn bluetooth on, but I find it off, if I quit bluetooth settings and go there again.

**Comment by 1Naim** [comment]
This can happen if the bluetooth service is off. Is it on for you?

**Comment by SeeDborg** [comment]
How do I check that please ?

**Comment by SeeDborg** [comment]
I launched the service by typing in the terminal : sudo systemctl enable --now bluetooth.service

It seems okay now !
Was there a simpler way to do this ?
Why don't you enable this service by default ?

Thanks for the help 👍

**Comment by ptr1337** [comment]
Its for new installations now as default enabled already (since 2411 release)

**Comment by SeeDborg** [comment]
It's strange because I installed with : cachyos-handheld-linux-241110.iso and it was off by default.
