### ISSUE TITLE
Network interface goes down randomly

### ISSUE THREAD

**Issue by spaghetticodez** [CachyOS/distribution#68]
Having strange issue (might be kernel related 6.9+). Network interface seems to crash? Only thing that seems to work is interface restart or full system restart and works from hours to minutes (seems to be random?).

Logs - https://paste.cachyos.org/p/3cc4971.log

Temp. solution: sudo ip link set .name. down and up fixes it for a while and then drops again.

Just for background, tested on POP-OS Live USB with 6.9 kernel, there was stable for 2h while testing, not sure if it is related.

**Comment by ptr1337** [comment]
You can try to disable aspm, otherwise I would sugges you to report it on the kernel bug tracker.
```
[ 1383.891489] r8169 0000:0e:00.0 enp14s0: NETDEV WATCHDOG: CPU: 16: transmit queue 0 timed out 5002 ms
[ 1383.904330] r8169 0000:0e:00.0 enp14s0: rtl_rxtx_empty_cond == 0 (loop: 42, delay: 100).
[ 1393.577333] [UFW BLOCK] IN=enp14s0 OUT= MAC=01:00:5e:00:00:fc:a8:42:a1:3d:2d:e0:08:00 SRC=192.168.0.1 DST=224.0.0.252 LEN=36 TOS=0x00 PREC=0x00 TTL=1 ID=42136 PROTO=2 
[ 1418.421805] Code: fa 41 55 41 54 55 89 f5 53 48 89 fb 48 83 ec 08 4c 8b 67 58 0f b6 05 83 36 d8 02 84 c0 0f 84 9a 00 00 00 0f b6 05 73 36 d8 02 <41> 83 7c 24 08 03 4c 8d 2d 86 84 cb 02 88 83 68 01 00 00 7e 0f 49
[ 1439.512815] r8169 0000:0e:00.0 enp14s0: Link is Down
[ 1439.524651] r8169 0000:0e:00.0 enp14s0: rtl_rxtx_empty_cond == 0 (loop: 42, delay: 100).
[ 1443.520213] RTL8226B_RTL8221B 2.5Gbps PHY r8169-0-e00:00: attached PHY driver (mii_bus:phy_addr=r8169-0-e00:00, irq=MAC)
[ 1443.664371] r8169 0000:0e:00.0 enp14s0: Link is Down
[ 1446.503341] r8169 0000:0e:00.0 enp14s0: Link is Up - 1Gbps/Full - flow control off
```

**Comment by NextWork123** [comment]
> Having strange issue (might be kernel related 6.9+). Network interface seems to crash? Only thing that seems to work is interface restart or full system restart and works from hours to minutes (seems to be random?).
> 
> Logs - https://paste.cachyos.org/p/3cc4971.log
> 
> Temp. solution: sudo ip link set .name. down and up fixes it for a while and then drops again.
> 
> Just for background, tested on POP-OS Live USB with 6.9 kernel, there was stable for 2h while testing, not sure if it is related.

can you tell me if you have an error on journal like that? `igc failed to read reg 0xc030` if you have the igc failed to read it is a power energy thing of ASPM and you can disable that on bios or with some boot flags on my pc i was using these flags: `pcie_port_pm=off` == it disable power management of PCIE port you can too force the ASPM policy to be perfomance: `pcie_aspm.policy=performance`

**Comment by spaghetticodez** [comment]
> > Having strange issue (might be kernel related 6.9+). Network interface seems to crash? Only thing that seems to work is interface restart or full system restart and works from hours to minutes (seems to be random?).
> > Logs - https://paste.cachyos.org/p/3cc4971.log
> > Temp. solution: sudo ip link set .name. down and up fixes it for a while and then drops again.
> > Just for background, tested on POP-OS Live USB with 6.9 kernel, there was stable for 2h while testing, not sure if it is related.
> 
> can you tell me if you have an error on journal like that? `igc failed to read reg 0xc030` if you have the igc failed to read it is a power energy thing of ASPM and you can disable that on bios or with some boot flags on my pc i was using these flags: `pcie_port_pm=off` == it disable power management of PCIE port you can too force the ASPM policy to be perfomance: `pcie_aspm.policy=performance`

journalctl | grep "igc failed to read reg 0xc030" seems to give no result at the moment, i will try to disable ASPM and see what are the result. Thanks.

**Comment by spaghetticodez** [comment]
Let's close this issue here, as kernel 6.9+ works fine, tested on POP.
