### ISSUE TITLE
Can not create a socket for launching a KIO worker for protocol 'file'

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/distribution#69]
https://bugs.kde.org/show_bug.cgi?id=497090

**Comment by ptr1337** [comment]
I can not reproduce this issue

**Comment by dougg0k** [comment]
I didnt mess with anything related afaik, so, unsure on why.

**Comment by dougg0k** [comment]
Also this is the second time it happened from a fresh install using cachyos kde. Any idea what kind if setting or package that could affect this?

**Comment by dougg0k** [comment]
There is an error that often occur on the command line, and only have happened on KDE, randomly, even when you type a command like `pacman -S`.

I wonder if it's related, as the protocol error are related to opening files and sometimes folders depending on the application.

`error: could not get current working directory`

```
...
 Total (2/2)
(2/2) checking keys in keyring
(2/2) checking package integrity
(2/2) loading package files
(2/2) checking for file conflicts
:: Processing package changes...
error: could not get current working directory
(1/2) installing ....
(2/2) installing ...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
...
```

**Comment by dougg0k** [comment]
I stopped the systemctl service and tried, the issue persist.

**Comment by dougg0k** [comment]
There is a `kioworker` profile at ` /etc/apparmor.d/kioworker`.

I wonder what would require to fix it.

**Comment by dougg0k** [comment]
I opened a request for a fix. https://github.com/roddhjav/apparmor.d/issues/630
